export const options = [
"Devil fish",
"Crimson Jobfish",
"White Hake",
"Atlantic Chub Mackerel",
"American Lobster",
"Yellowtail Rockfish",
"Bocaccio",
"Sugar Kelp",
"Sablefish",
"Atlantic Halibut",
"Shortspine Thornyhead",
"Canary Rockfish",
"Black Grouper",
"Striped Marlin",
"Blueline Tilefish",
"Red Hake",
"Atlantic Sharpnose Shark",
"Pacific Sardine",
"Pacific Oyster",
"Northern Quahog",
"Geoduck",
"Eastern Oyster",
"Blue Mussel",
"Atlantic Salmon",
"Butterfish",
"Winter Skate",
"Pink Salmon",
"Atlantic Northern Shrimp",
"North Pacific Swordfish",
"Atlantic Mackerel",
"Atlantic Bigeye Tuna",
"North Atlantic Albacore Tuna",
"Acadian Redfish",
"Atlantic Skipjack Tuna",
"Atlantic Sea Scallop",
"Atlantic Pollock",
"Atlantic Yellowfin Tuna",
"Longfin Inshore Squid",
"Scup",
"Pink Shrimp",
"White Shrimp",
"Silver Hake",
"Pacific Skipjack Tuna",
"North Atlantic Swordfish",
"Brown Rock Shrimp",
"Yellowtail Flounder",
"Winter Flounder",
"Coho Salmon",
"Chum Salmon",
"Brown Shrimp",
"Pacific Mackerel",
"Pacific Bluefin Tuna",
"Opah",
"Atlantic Herring",
"Vermilion Snapper",
"Atlantic Blacktip Shark",
"Haddock",
"Chinook Salmon",
"Pacific Bigeye Tuna",
"Atlantic Shortfin Mako Shark",
"Atlantic Common Thresher Shark",
"Yellowfin Sole",
"Pacific Yellowfin Tuna",
"Pacific Whiting",
"Spanish Mackerel",
"Rock Sole",
"Pacific Wahoo",
"King Mackerel",
"Greenland Turbot",
"California Market Squid",
"Atlantic Wahoo",
"Gag Grouper",
"Flathead Sole",
"Summer Flounder",
"Rex Sole",
"Red Grouper",
"English Sole",
"Dover Sole",
"Caribbean Spiny Lobster",
"Pacific Albacore Tuna",
"Wreckfish",
"Queen Conch",
"Red King Crab",
"Pacific Spiny Dogfish",
"Pacific Halibut",
"Atlantic Spiny Dogfish",
"Arrowtooth Flounder",
"Alaska Snow Crab",
"Ocean Quahog",
"Gray Triggerfish",
"Bluefish",
"Black Sea Bass",
"Petrale Sole",
"Greater Amberjack",
"Pacific Common Thresher Shark",
"Pacific Cod",
"Pacific Blue Marlin",
"Northern Anchovy",
"Lingcod",
"Atlantic Striped Bass",
"Atlantic Surfclam",
"Pacific Shortfin Mako Shark",
"Pacific Ocean Perch",
"Pacific Mahimahi",
"Widow Rockfish",
"Western Atlantic Bluefin Tuna",
"Tilefish",
"Red Snapper",
"Sockeye Salmon",
"Alaska Pollock",
"Monkfish",
"Atlantic Mahi Mahi",
"Cobia",
"Atlantic Cod",
"Tiger Prawn",
"Octopus",
"Japanese Flying Squid",
"Humboldt Squid",
"Crucian Carp",
"Bighead Carp",
"Mozambique_Tilapia",
"Blue Tilapia",
"Nile tilapia",
"American Paddlefish"
]
export const options1 = [
"Devil_fish",
"Crimson_Jobfish",
"White_Hake",
"Atlantic_Chub_Mackerel",
"American_Lobster",
"Yellowtail_Rockfish",
"Bocaccio",
"Sugar_Kelp",
"Sablefish",
"Atlantic_Halibut",
"Shortspine_Thornyhead",
"Canary_Rockfish",
"Black_Grouper",
"Striped_Marlin",
"Blueline_Tilefish",
"Red_Hake",
"Atlantic_Sharpnose_Shark",
"Pacific_Sardine",
"Pacific_Oyster",
"Northern_Quahog",
"Geoduck",
"Eastern_Oyster",
"Blue_Mussel",
"Atlantic_Salmon",
"Butterfish",
"Winter_Skate",
"Pink_Salmon",
"Atlantic_Northern_Shrimp",
"North_Pacific_Swordfish",
"Atlantic_Mackerel",
"Atlantic_Bigeye_Tuna",
"North_Atlantic_Albacore_Tuna",
"Acadian_Redfish",
"Atlantic_Skipjack_Tuna",
"Atlantic_Sea_Scallop",
"Atlantic_Pollock",
"Atlantic_Yellowfin_Tuna",
"Longfin_Inshore_Squid",
"Scup",
"Pink_Shrimp",
"White_Shrimp",
"Silver_Hake",
"Pacific_Skipjack_Tuna",
"North_Atlantic_Swordfish",
"Brown_Rock_Shrimp",
"Yellowtail_Flounder",
"Winter_Flounder",
"Coho_Salmon",
"Chum_Salmon",
"Brown_Shrimp",
"Pacific_Mackerel",
"Pacific_Bluefin_Tuna",
"Opah",
"Atlantic_Herring",
"Vermilion_Snapper",
"Atlantic_Blacktip_Shark",
"Haddock",
"Chinook_Salmon",
"Pacific_Bigeye_Tuna",
"Atlantic_Shortfin_Mako_Shark",
"Atlantic_Common_Thresher_Shark",
"Yellowfin_Sole",
"Pacific_Yellowfin_Tuna",
"Pacific_Whiting",
"Spanish_Mackerel",
"Rock_Sole",
"Pacific_Wahoo",
"King_Mackerel",
"Greenland_Turbot",
"California_Market_Squid",
"Atlantic_Wahoo",
"Gag_Grouper",
"Flathead_Sole",
"Summer_Flounder",
"Rex_Sole",
"Red_Grouper",
"English_Sole",
"Dover_Sole",
"Caribbean_Spiny_Lobster",
"Pacific_Albacore_Tuna",
"Wreckfish",
"Queen_Conch",
"Red_King_Crab",
"Pacific_Spiny_Dogfish",
"Pacific_Halibut",
"Atlantic_Spiny_Dogfish",
"Arrowtooth_Flounder",
"Alaska_Snow_Crab",
"Ocean_Quahog",
"Gray_Triggerfish",
"Bluefish",
"Black_Sea_Bass",
"Petrale_Sole",
"Greater_Amberjack",
"Pacific_Common_Thresher_Shark",
"Pacific_Cod",
"Pacific_Blue_Marlin",
"Northern_Anchovy",
"Lingcod",
"Atlantic_Striped_Bass",
"Atlantic_Surfclam",
"Pacific_Shortfin_Mako_Shark",
"Pacific_Ocean_Perch",
"Pacific_Mahimahi",
"Widow_Rockfish",
"Western_Atlantic_Bluefin_Tuna",
"Tilefish",
"Red_Snapper",
"Sockeye_Salmon",
"Alaska_Pollock",
"Monkfish",
"Atlantic_Mahi_Mahi",
"Cobia",
"Atlantic_Cod",
"Tiger_Prawn",
"Octopus",
"Japanese_Flying Squid",
"Humboldt_Squid",
"Crucian_Carp",
"Bighead_Carp",
"Mozambique_Tilapia",
"Blue_Tilapia",
"Nile_tilapia",
"American_Paddlefish",
]

//default state for the fish class. Just in case someone loads into the fish page. 
export const default_fish = {
    title: "Atlantic_Wahoo",
    name: "Atlantic Wahoo",
    url: "https://www.fishwatch.gov/",
    description: "Atlantic wahoo grow fast, up to 8 feet and 158 pounds, though they are commonly between 3.3 and 5.4 feet long.They have a short life span, up to 5 or 6 years.They are able to reproduce at about 1 year old. For males, this is when they reach 2.8 feet in length, and for females, when they reach 3.3 feet.Atlantic wahoo spawn multiple times throughout the spawning season.They are very productive, releasing a half-million to 45 million eggs per year to compensate for eggs that might not survive to adulthood.They mainly feed on squid and fish, including frigate mackerel, butterfish, porcupine fish, and round herring. They generally compete with tuna, but can feed on larger prey by using their extremely sharp teeth to render prey into bite-size pieces.A number of predators that share their habitat feed on young wahoo.",
    status: "There are four stocks of wahoo: a South Atlantic/Gulf of Mexico stock, a Puerto Rico stock, a St. Croix stock, and a St. Thomas/St. John stock. According to the most recent stock assessments:The South Atlantic/Gulf of Mexico stock has not been assessed and the population status and fishing rateare unknown. However, catch limits are in place for this stock.The Puerto Rico stock has not been assessed so the population size is unknown, but the stock is not subject to overfishing based on 2019 catch data.The St. Croixstock has not been assessed so the population size is unknown, but the stock is not subject to overfishing based on 2021catch data.The St. Thomas/St. Johnstock has not been assessed so the population size is unknown, but the stock is not subject to overfishing based on 2021catch data.Atlantic wahoo can handle relatively high fishing rates, but precautionary management seeks to maintain current harvest levels.",
    scientific: "Acanthocybium solandri",
    health_benefits: "Atlantic wahoo is an excellent source of low-fat protein.",
    quote: "U.S. wild-caught Atlantic wahoo is a smart seafood choice because it is sustainably managed and responsibly harvested under U.S. regulations.",
    tags: [],
    img: "",
    cuisine_img: "",
    liked: false,
    Taste: "Mild.",
    Texture: "Firm with a large, circular flake."
}
//Gallery imgs default value states.
//Replace whenever we call the google api to get new images for the fish gallery
export const gallery_imgs = {
    img1: "https://static.pexels.com/photos/162319/cat-pet-furry-face-162319.jpeg",
    img2: "https://static.pexels.com/photos/162319/cat-pet-furry-face-162319.jpeg",
    img3: "https://static.pexels.com/photos/162319/cat-pet-furry-face-162319.jpeg",
    img4: "https://static.pexels.com/photos/162319/cat-pet-furry-face-162319.jpeg",
    img5: "https://static.pexels.com/photos/162319/cat-pet-furry-face-162319.jpeg",
    img6: "https://static.pexels.com/photos/162319/cat-pet-furry-face-162319.jpeg",
    img7: "https://static.pexels.com/photos/162319/cat-pet-furry-face-162319.jpeg",
    img8: "https://static.pexels.com/photos/162319/cat-pet-furry-face-162319.jpeg",
    img9: "https://static.pexels.com/photos/162319/cat-pet-furry-face-162319.jpeg"
}

/*
blue #A8DBFF 
pink #F39C9C 
green #A2F58C 
*/