export const members1= ['Crimson Jobfish',
  'White Hake',
  'Atlantic Chub Mackerel',
  'Yellowtail Rockfish',
  'Bocaccio',
  'Sablefish',
  "Crucian Carp",
"Bighead Carp",
"Mozambique_Tilapia",
"Blue Tilapia",
"Nile tilapia",
"American Paddlefish",
  'Atlantic Halibut',
  'Shortspine Thornyhead',
  'Canary Rockfish',
  'Black Grouper',
  'Striped Marlin',
  'Blueline Tilefish',
  'Red Hake',
  'Pacific Sardine',
  'Blue Mussel',
  'Atlantic Salmon',
  'Butterfish',
  'Winter Skate',
  'Pink Salmon',
  'North Pacific Swordfish',
  'Atlantic Mackerel',
  'Atlantic Bigeye Tuna',
  'North Atlantic Albacore Tuna',
  'Acadian Redfish',
  'Atlantic Skipjack Tuna',
  'Atlantic Pollock',
  'Atlantic Yellowfin Tuna',
  'Scup',
  'Silver Hake',
  'Pacific Skipjack Tuna',
  'North Atlantic Swordfish',
  'Yellowtail Flounder',
  'Winter Flounder',
  'Coho Salmon',
  'Chum Salmon',
  'Pacific Mackerel',
  'Pacific Bluefin Tuna',
  'Opah',
  'Atlantic Herring',
  'Vermilion Snapper',
  'Haddock',
  'Chinook Salmon',
  'Pacific Bigeye Tuna',
  'Yellowfin Sole',
  'Pacific Yellowfin Tuna',
  'Pacific Whiting',
  'Spanish Mackerel',
  'Rock Sole',
  'Pacific Wahoo',
  'King Mackerel',
  'Greenland Turbot',
  ]

  export const members2 = ['Atlantic Wahoo',
  'Gag Grouper',
  'Flathead Sole',
  'Summer Flounder',
  'Rex Sole',
  'Red Grouper',
  'English Sole',
  'Dover Sole',
  'Pacific Albacore Tuna',
  'Wreckfish',
  'Pacific Spiny Dogfish',
  'Pacific Halibut',
  'Atlantic Spiny Dogfish',
  'Arrowtooth Flounder',
  'Gray Triggerfish',
  'Bluefish',
  'Black Sea Bass',
  'Petrale Sole',
  'Greater Amberjack',

  'Pacific Cod',
  'Pacific Blue Marlin',
  'Northern Anchovy',
  'Lingcod',
  'Atlantic Striped Bass',

  'Pacific Ocean Perch',
  'Pacific Mahimahi',
  'Widow Rockfish',
  'Western Atlantic Bluefin Tuna',
  'Tilefish',
  'Red Snapper',
  'Sockeye Salmon',
  'Alaska Pollock',
  'Monkfish',
  'Atlantic Mahi Mahi',
  'Cobia',
  'Atlantic Cod']